version: '3.8'

services:
  chat-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: heberghub-chat-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DISCORD_TOKEN=VOTRE_TOKEN_DISCORD
      - DISCORD_GUILD_ID=VOTRE_ID_SERVEUR_DISCORD
      - DISCORD_FORUM_CHANNEL_ID=VOTRE_ID_SALON_FORUM
      - DISCORD_SUPPORT_ROLE_ID=VOTRE_ID_ROLE_SUPPORT
    volumes:
      - ./logs:/app/logs

networks:
  default:
    driver: bridge